# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import project_name.apps.core.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('total_row', models.PositiveSmallIntegerField(default=0)),
                ('total_column', models.PositiveSmallIntegerField(default=0)),
                ('price_soles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_dollars', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_initial', models.DateField(blank=True)),
                ('date_final', models.DateField(blank=True, null=True)),
                ('coin_kas', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'payment plan',
                'verbose_name_plural': 'payment plans',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('codename', models.CharField(max_length=80, unique=True, verbose_name='codename')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
            },
            managers=[
                ('objects', project_name.apps.core.manager.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('codename', models.CharField(max_length=80, unique=True, verbose_name='codename')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpacePlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('plan_type', models.CharField(choices=[('', '--Choose--'), ('PLN-1', 'Free'), ('PLN-2', 'Basic'), ('PLN-3', 'Bronze'), ('PLN-4', 'Silver'), ('PLN-5', 'Gold')], default='PLN-1', max_length=80, verbose_name='plan type')),
                ('size', models.PositiveSmallIntegerField(default=0)),
                ('price_soles', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_dollars', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_initial', models.DateField(blank=True)),
                ('date_final', models.DateField(blank=True, null=True)),
                ('coin_kas', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'space plan',
                'verbose_name_plural': 'space plans',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
            managers=[
                ('objects', project_name.apps.core.manager.TeamManager()),
            ],
        ),
    ]
