# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20171104_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Help', 'verbose_name_plural': 'Helps'},
        ),
        migrations.AlterUniqueTogether(
            name='help',
            unique_together=set([('name',)]),
        ),
    ]
