from django.utils.translation import ugettext_lazy as _

CODE_TEXT_EDIT = 'EDIT'
TEXT_MSG_SUCCESS = _('Data saved correctly')
TEXT_MSG_ERROR = _('There was an error saving information')
TEXT_MSG_WARNING = _('It required to complete required fields')
STATUS_MSG_TAGS = {
    'success': TEXT_MSG_SUCCESS,
    'error': TEXT_MSG_ERROR,
    'warning': TEXT_MSG_WARNING,
}

NAME_SELECT_DEFAULT = _('--Choose--')
SELECT_DEFAULT_ = [('', NAME_SELECT_DEFAULT)]
SELECT_DEFAULT = (('', NAME_SELECT_DEFAULT),)
DISABLED = 'DISABLED'
ENABLED = 'ENABLED'
STATUS_MODEL1 = (
    (ENABLED, _('Enabled')),
    (DISABLED, _('Disabled')),
)

# ITEMS IDENTITY DOCUMENT
CODE_DOCUMENT_DNI = 'DOC-1'
CODE_DOCUMENT_RUC = 'DOC-2'
CODE_DOCUMENT_PASSPORT = 'DOC-3'
DOCUMENT_DNI_STRING = (CODE_DOCUMENT_DNI, _('DNI'))
DOCUMENT_RUC_STRING = (CODE_DOCUMENT_RUC, _('RUC'))
DOCUMENT_PASSPORT_STRING = (CODE_DOCUMENT_PASSPORT, _('PASSPORT'))
TYPE_IDENTITY_DOCUMENT_OPTIONS = (
    DOCUMENT_DNI_STRING, DOCUMENT_RUC_STRING, DOCUMENT_PASSPORT_STRING,
)

# ITEMS TRIBUTE PERSON
CODE_TRIBUTE_PERSON_NATURAL = 'PERS-1'
CODE_TRIBUTE_PERSON_JURIDICAL = 'PERS-2'
TRIBUTE_PERSON_NATURAL_STRING = (CODE_TRIBUTE_PERSON_NATURAL, _('Natural'))
TRIBUTE_PERSON_JURIDICAL_STRING = (CODE_TRIBUTE_PERSON_JURIDICAL, _('Legal'))

TRIBUTE_PERSON_OPTIONS = (
    TRIBUTE_PERSON_NATURAL_STRING, TRIBUTE_PERSON_JURIDICAL_STRING,
)

# ITEMS GENDER
CODE_GENDER_MALE = 'GEN-1'
CODE_GENDER_FEMALE = 'GEN-2'
GENDER_MALE_STRING = (CODE_GENDER_MALE, _('Male'))
GENDER_FEMALE_STRING = (CODE_GENDER_FEMALE, _('Female'))
TYPE_GENDER_OPTIONS = (
    GENDER_MALE_STRING, GENDER_FEMALE_STRING,
)

# ITEMS CIVIL STATUS
CODE_CIVIL_STATUS_SINGLE = 'CVS-1'
CODE_CIVIL_STATUS_MARRIED = 'CVS-2'
CODE_CIVIL_STATUS_WIDOWED = 'CVS-3'
CODE_CIVIL_STATUS_DIVORCED = 'CVS-4'
CODE_CIVIL_STATUS_SEPARATED = 'CVS-5'
CIVIL_STATUS_SINGLE_STRING = (CODE_CIVIL_STATUS_SINGLE, _('Single'))
CIVIL_STATUS_MARRIED_STRING = (CODE_CIVIL_STATUS_MARRIED, _('Married'))
CIVIL_STATUS_WIDOWED_STRING = (CODE_CIVIL_STATUS_WIDOWED, _('Widowed'))
CIVIL_STATUS_DIVORCED_STRING = (CODE_CIVIL_STATUS_DIVORCED, _('Divorced'))
CIVIL_STATUS_SEPARATED_STRING = (CODE_CIVIL_STATUS_SEPARATED, _('Separated'))
TYPE_CIVIL_STATUS_OPTIONS = (
    CIVIL_STATUS_SINGLE_STRING, CIVIL_STATUS_MARRIED_STRING,
    CIVIL_STATUS_WIDOWED_STRING, CIVIL_STATUS_DIVORCED_STRING,
    CIVIL_STATUS_SEPARATED_STRING,
)

# ITEMS PLAN COMMERCIAL
CODE_PLAN_ONE = 'PLN-1'
CODE_PLAN_TWO = 'PLN-2'
CODE_PLAN_THREE = 'PLN-3'
CODE_PLAN_FOUR = 'PLN-4'
CODE_PLAN_FIVE = 'PLN-5'
PLAN_ONE_STRING = (CODE_PLAN_ONE, _('Free'))
PLAN_TWO_STRING = (CODE_PLAN_TWO, _('Basic'))
PLAN_THREE_STRING = (CODE_PLAN_THREE, _('Bronze'))
PLAN_FOUR_STRING = (CODE_PLAN_FOUR, _('Silver'))
PLAN_FIVE_STRING = (CODE_PLAN_FIVE, _('Gold'))

TYPE_PLAN_OPTIONS = (
    PLAN_ONE_STRING, PLAN_TWO_STRING, PLAN_THREE_STRING,
    PLAN_FOUR_STRING, PLAN_FIVE_STRING
)

# ITEMS ROLES COMPANY
CODE_ROLE_ONE = 'ROL-1'
CODE_ROLE_TWO = 'ROL-2'
CODE_ROLE_THREE = 'ROL-3'
ROLE_ONE_STRING = (CODE_ROLE_ONE, _('ADMIN'))
ROLE_TWO_STRING = (CODE_ROLE_TWO, _('DATOS'))
ROLE_THREE_STRING = (CODE_ROLE_THREE, _('OPERADOR'))

TYPE_ROLE_OPTIONS = (
    ROLE_ONE_STRING, ROLE_TWO_STRING, ROLE_THREE_STRING,
)
